[package]
name = "bevy-fps-ui"
version = "0.1.0"
authors = ["kamii"]
edition = "2021"

[dependencies]
bevy = "0.13.2"

[[example]]
name = "basic-example"
path = "basic.rs"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
